CREATE SCHEMA users;

CREATE TABLE IF NOT EXISTS users.info (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE rooms (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE messages (
  id UUID PRIMARY KEY,
  room_name VARCHAR(255),
  author VARCHAR(255),
  text TEXT,
  timestamp TIMESTAMP
);