CREATE SCHEMA users;
    

CREATE TABLE IF NOT EXISTS users.info (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  userid VARCHAR(255) NOT NULL
);